server:
  port: 8081
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://54.38.52.142:5432/postgres
    username: proarea
    password: disnerigdsf3239nfwepnf
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

application:
  api.version.prefix: /
  security:
    password:
      sault1: y2R1D7gk5x10PadS4EfX
      sault2: CuvPf2xQ9B5DPS05uqPP
    jwt:
      tokenExpirationMinutes: 1440
      tokenIssuer: http://localhost:8081/
      tokenSigningKey: asdf354kvkjd09567lkjasdf723jdlijr
swagger:
  apiTitle: Board Service
  apiDescription: Board Service API
  groupName: board
  securedPaths:
  - /url
  - /url/**
